name:                poibattle2psql
version:             0.1.0.0
github:              "Javran/poibattle2psql"
license:             BSD3
author:              "Javran Cheng"
maintainer:          "javran.c@gmail.com"
copyright:           "Copyright: (c) 2019 Javran Cheng"

description:         Export poi's battle data to PostgreSQL.

dependencies:
- aeson
- base
- bytestring
- containers
- dhall
- foldl
- hasql
- mtl
- postgresql-binary
- system-filepath
- text
- time
- turtle

executables:
  pb2psql:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
