name:                shady-zox
version:             0.1.0.0
github:              "Javran/shady-zox"
license:             BSD3
author:              "Javran Cheng"
maintainer:          "javran.c@gmail.com"
copyright:           "Copyright: (c) 2019 Javran Cheng"

description:         description

dependencies:
- base
- base64-bytestring
- bytestring
- http-client
- http-client-tls
- http-types
- text

executables:
  demo:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
