name:                haskell-ffi
version:             0.1.0.0
github:              "Javran/haskell-ffi"
license:             BSD3
author:              "Javran Cheng"
maintainer:          "javran.c@gmail.com"
copyright:           "Copyright: (c) 2019 Javran Cheng"

description:         description

dependencies:
- base

executables:
  demo:
    main:                Main.hs
    source-dirs:         src
    c-sources:
    - c_src/neumaier.h
    - c_src/neumaier.c
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
