name: diagrams-playground
version: 0.1.0.0
github: Javran/diagrams-playground
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2019 Javran Cheng"

description: description

dependencies:
- base
- diagrams-core
- diagrams-lib
- diagrams-cairo

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2

executables:
  demo:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - diagrams-playground
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - diagrams-playground
      - QuickCheck
      - hspec
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
