name:                overlayer
version:             0.1.0.0
github:              "githubuser/overlayer"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

dependencies:
- base
- turtle
- http-client
- http-client-tls
- bytestring
- text
- aeson
- unordered-containers

executables:
  overlayer:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
