name:                proc-parser
version:             0.1.0.0
github:              "Javran/misc/proc-parser"
license:             BSD3
author:              "Javran Cheng"
maintainer:          "javran.c@gmail.com"
copyright:           "Copyright: (c) 2019 Javran Cheng"

description:         description

dependencies:
- attoparsec
- base
- bytestring
- scientific

executables:
  demo:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
