- ignore: {name: Avoid lambda using `infix`}
- ignore: {name: Use uncurry}
- ignore: {name: Use camelCase}
- ignore: {name: Use section}
- ignore: {name: Use newtype instead of data}
- ignore: {name: Reduce duplication}
