name: matchpb
version: 0.1.0.0
github: Javran/matchpb
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2019 Javran Cheng"

description: description

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

extra-source-files: proto/**/*.proto

dependencies:
- base
- bytestring

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
    - proto-lens-runtime
    - proto-lens
  exposed-modules:
    - Proto.MatchingResult
    - MatchMain

executables:
  demo:
    main: Main.hs
    source-dirs: exe
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - matchpb
