name:                kc-static-get
version:             0.1.0.0
github:              "Javran/kc-static-get"
license:             BSD3
author:              "Javran Cheng"
maintainer:          "javran.c@gmail.com"
copyright:           "Copyright: (c) 2019 Javran Cheng"

description:         description

dependencies:
- base
- containers
- dhall
- text

executables:
  demo:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
