name:                kernel-tool
version:             0.1.0.0
github:              "Javran/kernel-tool"
license:             BSD3
author:              "Javran Cheng"
maintainer:          "javran.c@gmail.com"
copyright:           "Copyright: (c) 2019 Javran Cheng"

description:         description

dependencies:
- base
- turtle
- process
- containers
- text
- directory
- foldl
- natural-sort
- microstache
- unordered-containers
- aeson
- vector

executables:
  kernel-tool:
    main:                Main.hs
    source-dirs:         src
    other-modules:
    - Common
    - CommandSwitch
    - CommandInstall
    - CommandClean
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
