name: random-walk
version: 0.1.0.0
github: Javran/random-walk
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2019 Javran Cheng"

description: description

dependencies:
- async
- base
- reactive-banana
- tf-random
- mtl

executables:
  demo:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
