name: max-flow
version: 0.1.0.0
github: Javran/max-flow
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2019 Javran Cheng"

description: description

dependencies:
- base

data-files:
  - data/simple.dimacs

library:
  generated-exposed-modules: Paths_max_flow
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2

executables:
  demo:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - max-flow
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - max-flow
      - QuickCheck
      - hspec
    ghc-options:
      - -Wall
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
