name: output-sink
version: 0.1.0.0
github: Javran/output-sink
license: BSD3
author: Javran Cheng
maintainer: javran.c@gmail.com
copyright: "Copyright: (c) 2019 Javran Cheng"

description: description

dependencies:
- async
- base
- bytestring
- directory
- filepath
- process
- safe-exceptions

executables:
  demo:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
