name:                kc-sprite-tool
version:             0.1.0.0
github:              "Javran/kc-sprite-tool"
license:             BSD3
author:              "Javran Cheng"
maintainer:          "javran.c@gmail.com"
copyright:           "Copyright: (c) 2019 Javran Cheng"

description:         description

dependencies:
- aeson
- base
- containers
- filepath
- hip
- text
- unordered-containers

executables:
  demo:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
