name:    yesod-min
version: "0.0.0"

dependencies:
- base
- yesod-core

library:
  source-dirs: src

executables:
  demo:
    main: Main.hs
    source-dirs: exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesod-min
