name:                monad-par-playground
version:             0.1.0.0
github:              "Javran/monad-par-playground"
license:             BSD3
author:              "Javran Cheng"
maintainer:          "javran.c@gmail.com"
copyright:           "Copyright: (c) 2019 Javran Cheng"

description:         description

dependencies:
- base
- monad-par
- bytestring
- abstract-par

executables:
  demo:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
