name:                maze-gen
version:             0.1.0.0
github:              "Javran/maze-gen"
license:             BSD3
author:              "Javran Cheng"
maintainer:          "javran.c@gmail.com"
copyright:           "Copyright: (c) 2019 Javran Cheng"

description:         description

dependencies:
- base
- containers
- mtl
- text
- tf-random

executables:
  maze-gen:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
